# Node Build and Validate and deploy on master push
name: Push Master CI

on:
  push:
    branches: 
      - master
    paths:
      - '!README*'
      - '!LICENSE*'
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm ci, run validate
      run: |
        # TODO: set env for CI
        touch .env
        npm ci
        npm run validate

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use nodejs 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: npm ci
        run: npm ci
      - name: Checks and verifications
        run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
            echo $PWD
            ls -lasi
      - name: GCP Authentication
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: List Functions
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        with:
          args: functions list
#    - name: Deploy Function partners
#      uses: actions/gcloud/cli@master
#      env:
#        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
#      with:
#        args: functions deploy partners --runtime nodejs10 --trigger-http --source $PWD/src
