# Node Build and Validate and deploy on master push
name: Push Master CI

on:
  push:
    branches: 
      - master

    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm ci, run validate
      run: |
        # TODO: set env for CI
        touch .env
        npm ci
        npm run validate

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Checks and verifications
        run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
            echo $PWD
            ls -lasi
#    - name: GCP Authentication
#      uses: actions/gcloud/auth@master
#      env:
#        GCLOUD_AUTH: ${{ secrets.GCP_CLOUD_AUTH }}

